language: objective-c
osx_image: xcode6.4

env:
  global:                  # set env variables for your build
    - PROJECT_DIR="$TRAVIS_BUILD_DIR/Client/App/Prometheus"
    - INFO_PLIST="$PROJECT_DIR/Prometheus/Prometheus-Info.plist"
    - BUNDLE_DISPLAY_NAME="Misfit"
    - BUNDLE_IDENTIFIER="com.misfitwearables.Prometheus"

before_install:
  - curl "https://s3.amazonaws.com/misfit.sw.stg.epd-team/downloads/travis_install.sh" | bash
  - travis-ext install_fastlane
install:                   # install dependencies
  - travis-ext pod_install
before_script:             # before script, clean old data and prepare init data
  - travis-ext add_key
script:                    # build & lint & run tests
  - travis-ext build
  - travis-ext lint
  - travis-ext test
  - travis-ext hockey_deploy
after_script:
  - travis-ext remove_key
  - travis-ext coveralls

cache:
  cocoapods: true          # cache cocoapods
