language: java
env:
  global:
    - ARES_TOKEN="Lez0iSh8aM4V"

before_install:
  - curl "https://s3.amazonaws.com/misfit.sw.stg.epd-team/downloads/travis_install.sh" | bash
  - $TRAVIS_EXT install_ares
install:
  - $TRAVIS_EXT maven_install
script:
  - $TRAVIS_EXT build
  - $TRAVIS_EXT lint
  - $TRAVIS_EXT test
  - $TRAVIS_EXT ares_deploy
after_script:
  - $TRAVIS_EXT coveralls

cache:
  directories:
    - $HOME/.m2        # cache maven downloads
