sudo: true                 # explicitly enable sudo 
language: objective-c      # choose your language, here is a sample for oc project
osx_image: beta-xcode6.3   # choose your xcode version

env:
  global:                  # set env variables for your build
    - TRAVIS_EXT_HOME=$HOME/travis-ext                                            # required.
    - TRAVIS_EXT=$TRAVIS_EXT_HOME/travis-ext.sh                                   # required.
    - PROJECT_LANGUAGE=objective-c                                                # required.
    - PROJECT_DIR=$TRAVIS_BUILD_DIR/Client/App/Prometheus                         # optional. default is $TRAVIS_BUILD_DIR
    - 'DEVELOPER_NAME="iPhone Distribution: MISFIT WEARABLES CORPORATION"'        # required.
    - CERT_DIR=$TRAVIS_BUILD_DIR/certs                                            # required.
    - PROFILE_DIR=$TRAVIS_BUILD_DIR/provisioning_profiles                         # required.
    - PROFILE_NAME=comMisfitwearablesPrometheusAdhoc                              # required.
    - INFO_PLIST=Client/App/Prometheus/Prometheus/Prometheus-Info.plist           # required.
    - APP_NAME=Misfit                                                             # required.
    - BUNDLE_DISPLAY_NAME=Misfit                                                  # required.
    - BUNDLE_IDENTIFIER=com.misfitwearables.Prometheus                            # required.
    - AWS_ACCESS_KEY_ID=******                                                    # required.
    # AWS_SECRET_ACCESS_KEY=[secure]
    - secure: "****************"                                                  # required.

before_install:
  - git clone --depth=50 --branch=develop https://github.com/westmisfit/travis-ext.git $TRAVIS_EXT_HOME
  - $TRAVIS_EXT install_cocoapods
install:                   # install dependencies
  - sudo ./downloadShineSDK.sh vincent 123456
  - $TRAVIS_EXT pod_install
before_script:             # before script, clean old data and prepare init data
  # - rm -rf buildStaging/*  # clean old build output
  - $TRAVIS_EXT add_key
  - $TRAVIS_EXT udpate_bundle
script:                    # build & lint & run tests
  - sh build.sh            # custom build script instead $TRAVIS_EXT build
  - $TRAVIS_EXT lint
  - $TRAVIS_EXT test
after_success:
  - $TRAVIS_EXT hockey_deploy
after_script:
  - $TRAVIS_EXT remove_key
  - $TRAVIS_EXT coveralls

